-- MySQL Script generated by MySQL Workbench
-- Tue Jun 13 16:44:25 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema edxl_capv1_2_refimp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `edxl_capv1_2_refimp` ;

-- -----------------------------------------------------
-- Schema edxl_capv1_2_refimp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `edxl_capv1_2_refimp` DEFAULT CHARACTER SET utf8 ;
USE `edxl_capv1_2_refimp` ;

-- -----------------------------------------------------
-- Table `edxl_capv1_2_refimp`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edxl_capv1_2_refimp`.`category` ;

CREATE TABLE IF NOT EXISTS `edxl_capv1_2_refimp`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edxl_capv1_2_refimp`.`alert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edxl_capv1_2_refimp`.`alert` ;

CREATE TABLE IF NOT EXISTS `edxl_capv1_2_refimp`.`alert` (
  `identifier` VARCHAR(150) NOT NULL,
  `sender` VARCHAR(100) NULL DEFAULT NULL,
  `sent` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  `msgType` VARCHAR(50) NULL DEFAULT NULL,
  `source` VARCHAR(200) NULL DEFAULT NULL,
  `scope` VARCHAR(50) NULL DEFAULT NULL,
  `restriction` VARCHAR(200) NULL DEFAULT NULL,
  `code` VARCHAR(50) NULL DEFAULT NULL,
  `note` VARCHAR(150) NULL DEFAULT NULL,
  `references` VARCHAR(150) NULL DEFAULT NULL,
  `incidents` VARCHAR(100) NULL DEFAULT NULL,
  `info` VARCHAR(150) NULL DEFAULT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`identifier`, `category_id`),
  INDEX `fk_alert_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_alert_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `edxl_capv1_2_refimp`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `edxl_capv1_2_refimp`.`info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edxl_capv1_2_refimp`.`info` ;

CREATE TABLE IF NOT EXISTS `edxl_capv1_2_refimp`.`info` (
  `info` VARCHAR(150) NOT NULL,
  `language` VARCHAR(50) NULL DEFAULT NULL,
  `category` VARCHAR(50) NULL DEFAULT NULL,
  `event` VARCHAR(50) NULL DEFAULT NULL,
  `responseType` VARCHAR(50) NULL DEFAULT NULL,
  `urgency` VARCHAR(50) NULL DEFAULT NULL,
  `severity` VARCHAR(50) NULL DEFAULT NULL,
  `certainty` VARCHAR(50) NULL DEFAULT NULL,
  `audience` VARCHAR(50) NULL DEFAULT NULL,
  `eventCode` VARCHAR(50) NULL DEFAULT NULL,
  `effective` DATETIME NULL DEFAULT NULL,
  `onset` DATETIME NULL DEFAULT NULL,
  `expires` DATETIME NULL DEFAULT NULL,
  `senderName` VARCHAR(50) NULL DEFAULT NULL,
  `headline` VARCHAR(160) NULL DEFAULT NULL,
  `description` VARCHAR(1500) NULL DEFAULT NULL,
  `instruction` VARCHAR(1500) NULL DEFAULT NULL,
  `web` VARCHAR(150) NULL DEFAULT NULL,
  `contact` VARCHAR(250) NULL DEFAULT NULL,
  `parameter` VARCHAR(150) NULL DEFAULT NULL,
  `resource` VARCHAR(150) NULL DEFAULT NULL,
  `area` VARCHAR(150) NULL DEFAULT NULL,
  `alert_identifier` VARCHAR(150) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`info`, `alert_identifier`, `category_id`),
  INDEX `fk_info_alert1_idx` (`alert_identifier` ASC),
  INDEX `fk_info_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_info_alert1`
    FOREIGN KEY (`alert_identifier`)
    REFERENCES `edxl_capv1_2_refimp`.`alert` (`identifier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_info_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `edxl_capv1_2_refimp`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `edxl_capv1_2_refimp`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edxl_capv1_2_refimp`.`area` ;

CREATE TABLE IF NOT EXISTS `edxl_capv1_2_refimp`.`area` (
  `area` VARCHAR(150) NOT NULL,
  `areaDesc` VARCHAR(350) NULL DEFAULT NULL,
  `polygon` VARCHAR(350) NULL DEFAULT NULL,
  `circle` VARCHAR(50) NULL DEFAULT NULL,
  `geocode` VARCHAR(50) NULL DEFAULT NULL,
  `altitude` VARCHAR(50) NULL DEFAULT NULL,
  `ceiling` VARCHAR(50) NULL DEFAULT NULL,
  `info_info` VARCHAR(50) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`area`, `info_info`, `category_id`),
  INDEX `fk_area_info1_idx` (`info_info` ASC),
  INDEX `fk_area_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_area_info1`
    FOREIGN KEY (`info_info`)
    REFERENCES `edxl_capv1_2_refimp`.`info` (`info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_area_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `edxl_capv1_2_refimp`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `edxl_capv1_2_refimp`.`resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edxl_capv1_2_refimp`.`resource` ;

CREATE TABLE IF NOT EXISTS `edxl_capv1_2_refimp`.`resource` (
  `resource` VARCHAR(150) NOT NULL,
  `resourceDesc` VARCHAR(300) NULL DEFAULT NULL,
  `mimeType` VARCHAR(100) NULL DEFAULT NULL,
  `size` INT NULL DEFAULT NULL,
  `uri` VARCHAR(150) NULL DEFAULT NULL,
  `derefUri` VARCHAR(50) NULL DEFAULT NULL,
  `digest` VARCHAR(50) NULL DEFAULT NULL,
  `info_info` VARCHAR(50) NOT NULL,
  `info_alert_identifier` VARCHAR(50) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`resource`, `info_info`, `info_alert_identifier`, `category_id`),
  INDEX `fk_resource_info1_idx` (`info_info` ASC, `info_alert_identifier` ASC),
  INDEX `fk_resource_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_resource_info1`
    FOREIGN KEY (`info_info` , `info_alert_identifier`)
    REFERENCES `edxl_capv1_2_refimp`.`info` (`info` , `alert_identifier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `edxl_capv1_2_refimp`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `edxl_capv1_2_refimp`.`element`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edxl_capv1_2_refimp`.`element` ;

CREATE TABLE IF NOT EXISTS `edxl_capv1_2_refimp`.`element` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `required` TINYINT NULL,
  `conditional` TINYINT NULL,
  `repeatable` TINYINT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_element_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_element_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `edxl_capv1_2`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
